name: 每日更新拜訪行程

on:
  schedule:
    - cron: '0 22 * * *'  # 台灣時間上午 6 點（UTC 22:00 前一天）
    - cron: '0 5 * * *'   # 台灣時間下午 1 點（UTC 05:00）
  workflow_dispatch:     # 允許手動執行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 下載 Repo 原始碼
        uses: actions/checkout@v3

      - name: 安裝 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安裝必要套件
        run: pip install requests

      - name: 執行拜訪行程產出程式
        run: python generate_routes.py

      - name: 提交更新後的 routes.html
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add routes.html
          git commit -m "每日自動更新拜訪行程"
          git push
        continue-on-error: true
