name: 每日自動更新拜訪行程頁

on:
  schedule:
    - cron: '0 22 * * *'  # 每天台灣時間早上6點 (UTC+8)
  workflow_dispatch:      # 可手動執行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 下載原始碼
      uses: actions/checkout@v3

    - name: 安裝 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 安裝 requests 套件
      run: pip install requests

    - name: 執行產生行程頁
      run: python generate_routes.py

    - name: 上傳更新
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        git pull --rebase origin main
        git add .
        git commit -m "每日自動更新拜訪行程頁" || echo "No changes to commit"
        git push
