name: 每日更新拜訪行程頁

on:
  schedule:
    - cron: '0 22 * * *'  # 每天台灣早上 6 點 (UTC 時區)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 下載原始碼
        uses: actions/checkout@v3

      - name: 安裝 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝 requests 套件
        run: pip install requests

      - name: 安裝 pytz 套件
        run: pip install pytz

      - name: 執行產生行程頁
        run: python generate_routes.py

      - name: 上傳更新
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git pull
          git add Dou/routes.html
          git commit -m "自動更新拜訪行程頁"
          git push
