name: 每日更新拜訪行程頁

on:
  schedule:
    - cron: '0 22 * * *' # 每天台灣早上 6 點（UTC 時區）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 下載原始碼
        uses: actions/checkout@v3
      - name: 安裝 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: 安裝 requests 與 pytz
        run: pip install requests pytz
      - name: 產生 routes.html
        run: python generate_routes.py
      - name: 自動上傳更新
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull origin main --rebase || true
          git add routes.html
          git commit -m "每日自動更新拜訪行程頁" || echo "No changes to commit"
          git push origin main || echo "Push failed"
